# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 600)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: #ff8d01;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Encendido = QtWidgets.QPushButton(self.centralwidget)
        self.Encendido.setGeometry(QtCore.QRect(60, 450, 261, 71))
        self.Encendido.setStyleSheet("QPushButton#Encendido{\n"
"background-color: #55aa00;\n"
"border-radius: 15px;\n"
"color: #fff;\n"
"font-family: \'Roboto\';\n"
"font-size: 25px;\n"
"}\n"
"")
        self.Encendido.setObjectName("Encendido")
        self.CuadroCam = QtWidgets.QLabel(self.centralwidget)
        self.CuadroCam.setGeometry(QtCore.QRect(60, 60, 571, 331))
        self.CuadroCam.setStyleSheet("QLabel#CuadroCam{\n"
"    border-radius: 20px;\n"
"    background-color:#00ffff;\n"
"}")
        self.CuadroCam.setText("")
        self.CuadroCam.setAlignment(QtCore.Qt.AlignCenter)
        self.CuadroCam.setObjectName("CuadroCam")
        self.Apagado = QtWidgets.QPushButton(self.centralwidget)
        self.Apagado.setGeometry(QtCore.QRect(370, 450, 261, 71))
        self.Apagado.setStyleSheet("QPushButton#Apagado{\n"
"background-color: #e30000;\n"
"border-radius: 15px;\n"
"color: #fff;\n"
"font-family: \'Roboto\';\n"
"font-size: 25px;\n"
"}")
        self.Apagado.setObjectName("Apagado")
        self.Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Exit.setGeometry(QtCore.QRect(740, 20, 61, 51))
        self.Exit.setStyleSheet("")
        self.Exit.setText("")
        self.Exit.setFlat(True)
        self.Exit.setObjectName("Exit")
        self.ImgExit = QtWidgets.QLabel(self.centralwidget)
        self.ImgExit.setGeometry(QtCore.QRect(740, 10, 61, 71))
        self.ImgExit.setText("")
        self.ImgExit.setPixmap(QtGui.QPixmap("../../../Descargas/exit2.png"))
        self.ImgExit.setObjectName("ImgExit")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(650, 60, 81, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("iloveimg-resized/PPE_VEST.png"))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("iloveimg-resized/PPE_MASK.png"))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("iloveimg-resized/PPE_HAT.png"))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ChekMask = QtWidgets.QCheckBox(self.centralwidget)
        self.ChekMask.setGeometry(QtCore.QRect(730, 208, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ChekMask.setFont(font)
        self.ChekMask.setIconSize(QtCore.QSize(30, 30))
        self.ChekMask.setTristate(False)
        self.ChekMask.setObjectName("ChekMask")
        self.CheckVest = QtWidgets.QCheckBox(self.centralwidget)
        self.CheckVest.setGeometry(QtCore.QRect(730, 98, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CheckVest.setFont(font)
        self.CheckVest.setIconSize(QtCore.QSize(30, 30))
        self.CheckVest.setTristate(False)
        self.CheckVest.setObjectName("CheckVest")
        self.CheckHat = QtWidgets.QCheckBox(self.centralwidget)
        self.CheckHat.setGeometry(QtCore.QRect(730, 318, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CheckHat.setFont(font)
        self.CheckHat.setIconSize(QtCore.QSize(30, 30))
        self.CheckHat.setTristate(False)
        self.CheckHat.setObjectName("CheckHat")
        self.ImgExit.raise_()
        self.Encendido.raise_()
        self.CuadroCam.raise_()
        self.Apagado.raise_()
        self.Exit.raise_()
        self.verticalLayoutWidget.raise_()
        self.ChekMask.raise_()
        self.CheckVest.raise_()
        self.CheckHat.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 816, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.actionHola = QtWidgets.QAction(MainWindow)
        self.actionHola.setObjectName("actionHola")
        self.actionHola_2 = QtWidgets.QAction(MainWindow)
        self.actionHola_2.setObjectName("actionHola_2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Encendido.setText(_translate("MainWindow", "Encendido"))
        self.Apagado.setText(_translate("MainWindow", "Apagado"))
        self.ChekMask.setText(_translate("MainWindow", "Mask"))
        self.CheckVest.setText(_translate("MainWindow", "Vest"))
        self.CheckHat.setText(_translate("MainWindow", "Hat"))
        self.actionHola.setText(_translate("MainWindow", "Hola"))
        self.actionHola_2.setText(_translate("MainWindow", "Hola"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
